In [2]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LassoCV
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import make_scorer
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ShuffleSplit
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import statsmodels.formula.api as smf
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import AdaBoostRegressor, GradientBoostingRegressor, ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor
from QBUS2820 import rmse_jack, r2_jack 
from sklearn.linear_model import Ridge 
from sklearn.linear_model import Lasso
from sklearn.linear_model import RidgeCV
import xgboost as xgb
from sklearn.grid_search import GridSearchCV
from ExtraCode import getResultTable
from sklearn.model_selection import cross_val_score
from QBUS2820 import forward
from sklearn.linear_model import ElasticNet
from sklearn import preprocessing

In [116]:
getResultTable(method,pred)

Test RMSE         SE  Jack R2     SE  \
Forward                               23834.417   4933.468    0.884  0.047   
GBoost                                20918.845   3335.212    0.911  0.019   
AdaBoost                              26396.260   3445.265    0.858  0.023   
XGBoost                               20930.701   3433.914    0.910  0.020   
XGBoost, ada, GB                      20990.748   3686.173    0.910  0.022   
xg GB                                 20256.938   3491.853    0.916  0.020   
xg adaboost                           22014.324   3690.781    0.901  0.023   
XGBoost, random tree, GB              21014.092   3760.257    0.910  0.022   
xg Random tree                        21990.427   3808.881    0.901  0.023   
XGBoost, GBoost Random Forest         21014.092   3760.257    0.910  0.022   
LASSO_Alpha_zeropointone              33487.881   8253.967    0.771  0.104   
Ridge                                 22958.587   4912.274    0.892  0.045   
XGBoost, GBoost Random Forest Ridge   18687.310   2274.773    0.929  0.011   
XGBoost, GBoost Random Forest LASSO   20738.696   2924.153    0.912  0.016   
ENET                                  34151.039   8005.147    0.762  0.103   
XGBoost, GBoost Random Forest ENET   191867.789   5074.864   -6.523  0.916   
XGBoost, GBoost Ridge                 18162.316   1732.004    0.933  0.009   
XGBoost, GBoost Ridge Forward         18555.519   1777.839    0.930  0.012   
XGBoost, GBoost Ridge Forward Tree    18452.473   1817.337    0.930  0.009   
LASSO_Alpha_one                       34657.818   7340.865    0.755  0.097   
LASSO_Alpha                           33487.881   8253.967    0.771  0.104   
LASSO_Alpha                           34657.818   7340.865    0.755  0.097   
LASSO_Alpha                           35545.440   5477.616    0.742  0.080   
LASSO_Alpha                           38610.035   7084.392    0.695  0.107   
LASSO_Alpha                           47177.318  10181.112    0.545  0.180   
LASSO_Alpha                           60827.358  18733.094    0.244  0.399   
LASSO_Alpha                           75767.793  29097.395   -0.173  0.737   
LASSO_Alpha                           95091.167  43559.474   -0.848  1.322   
LASSO Standard                       191867.784   5074.863   -6.523  0.916   
Ridge Standard1                      191867.781   5074.861   -6.523  0.916   
Ridge alpha 5                         22676.776   5832.693    0.895  0.050   
Ridge alpha 0.001                     27154.854   5866.839    0.849  0.063   
Ridge alpha 0.01                      26955.637   5788.133    0.852  0.062   
Ridge alpha 10                        23009.669   6346.654    0.892  0.055   
Ridge alpha 20                        23532.883   6821.710    0.887  0.059   

                                            MAE  R-square  
Forward                               14042.658     0.884  
GBoost                                13764.739     0.911  
AdaBoost                              18521.883     0.858  
XGBoost                               13937.653     0.910  
XGBoost, ada, GB                      13907.523     0.910  
xg GB                                 13369.483     0.916  
xg adaboost                           14815.195     0.901  
XGBoost, random tree, GB              13862.684     0.910  
xg Random tree                        14686.106     0.901  
XGBoost, GBoost Random Forest         13862.684     0.910  
LASSO_Alpha_zeropointone              18309.952     0.771  
Ridge                                 13610.797     0.892  
XGBoost, GBoost Random Forest Ridge   12983.717     0.929  
XGBoost, GBoost Random Forest LASSO   13959.306     0.912  
ENET                                  18888.261     0.762  
XGBoost, GBoost Random Forest ENET   178661.326    -6.523  
XGBoost, GBoost Ridge                 12735.517     0.933  
XGBoost, GBoost Ridge Forward         12743.404     0.930  
XGBoost, GBoost Ridge Forward Tree    12912.083     0.930  
LASSO_Alpha_one              

In [32]:

def getResultTable(rows, predictions):
    columns=['Test RMSE', 'SE', 'Jack R2', 'SE', 'MAE', 'R-square']
    results=pd.DataFrame(0.0, columns=columns, index=rows)

    for row,pred in zip(range(0,len(rows)),predictions):
        results.iloc[row,0], results.iloc[row,1] = rmse_jack(y_test, pred)
        results.iloc[row,2], results.iloc[row,3] = (r2_jack(y_test, pred))
        results.iloc[row,4] = mean_absolute_error(y_test, pred)
        results.iloc[row,5] = r2_score(y_test,pred)
    return results.round(3)

In [25]:
data = pd.read_csv('Train6_2.csv')

In [26]:
data['OverallCondScale'] = 0
data['OverallQualScale'] = 0
#OverallCond
#OverallQual

In [27]:
data.head()
#Converts it
data.ix[data.OverallCond == 0, 'OverallCondScale'] = 1
data.ix[data.OverallCond == 1, 'OverallCondScale'] = 1
data.ix[data.OverallCond == 2, 'OverallCondScale'] = 1
data.ix[data.OverallCond == 3, 'OverallCondScale'] = 2
data.ix[data.OverallCond == 4, 'OverallCondScale'] = 2
data.ix[data.OverallCond == 5, 'OverallCondScale'] = 3
data.ix[data.OverallCond == 6, 'OverallCondScale'] = 3
data.ix[data.OverallCond == 7, 'OverallCondScale'] = 4
data.ix[data.OverallCond == 8, 'OverallCondScale'] = 4
data.ix[data.OverallCond == 9, 'OverallCondScale'] = 5
data.ix[data.OverallCond == 10, 'OverallCondScale'] = 5

data.ix[data.OverallQual == 0, 'OverallQualScale'] = 1
data.ix[data.OverallQual == 1, 'OverallQualScale'] = 1
data.ix[data.OverallQual == 2, 'OverallQualScale'] = 1
data.ix[data.OverallQual == 3, 'OverallQualScale'] = 2
data.ix[data.OverallQual == 4, 'OverallQualScale'] = 2
data.ix[data.OverallQual == 5, 'OverallQualScale'] = 3
data.ix[data.OverallQual == 6, 'OverallQualScale'] = 3
data.ix[data.OverallQual == 7, 'OverallQualScale'] = 4
data.ix[data.OverallQual == 8, 'OverallQualScale'] = 4
data.ix[data.OverallQual == 9, 'OverallQualScale'] = 5
data.ix[data.OverallQual == 10, 'OverallQualScale'] = 5


/Users/ChristopherHyland/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until


In [29]:
del data['OverallCond'] 
del data['OverallQual']

In [31]:
data.to_csv("Train6_3.csv", index=False)

In [32]:
data = pd.read_csv('Test6_2.csv')

In [33]:
data['OverallCondScale'] = 0
data['OverallQualScale'] = 0
#OverallCond
#OverallQual

In [34]:
data.head()
#Converts it
data.ix[data.OverallCond == 0, 'OverallCondScale'] = 1
data.ix[data.OverallCond == 1, 'OverallCondScale'] = 1
data.ix[data.OverallCond == 2, 'OverallCondScale'] = 1
data.ix[data.OverallCond == 3, 'OverallCondScale'] = 2
data.ix[data.OverallCond == 4, 'OverallCondScale'] = 2
data.ix[data.OverallCond == 5, 'OverallCondScale'] = 3
data.ix[data.OverallCond == 6, 'OverallCondScale'] = 3
data.ix[data.OverallCond == 7, 'OverallCondScale'] = 4
data.ix[data.OverallCond == 8, 'OverallCondScale'] = 4
data.ix[data.OverallCond == 9, 'OverallCondScale'] = 5
data.ix[data.OverallCond == 10, 'OverallCondScale'] = 5

data.ix[data.OverallQual == 0, 'OverallQualScale'] = 1
data.ix[data.OverallQual == 1, 'OverallQualScale'] = 1
data.ix[data.OverallQual == 2, 'OverallQualScale'] = 1
data.ix[data.OverallQual == 3, 'OverallQualScale'] = 2
data.ix[data.OverallQual == 4, 'OverallQualScale'] = 2
data.ix[data.OverallQual == 5, 'OverallQualScale'] = 3
data.ix[data.OverallQual == 6, 'OverallQualScale'] = 3
data.ix[data.OverallQual == 7, 'OverallQualScale'] = 4
data.ix[data.OverallQual == 8, 'OverallQualScale'] = 4
data.ix[data.OverallQual == 9, 'OverallQualScale'] = 5
data.ix[data.OverallQual == 10, 'OverallQualScale'] = 5


/Users/ChristopherHyland/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until


In [36]:
del data['OverallCond'] 
del data['OverallQual']

In [37]:
data.to_csv("Test6_3.csv", index=False)

In [38]:
data = pd.read_csv('Train6_3.csv')
y_price = data.pop('SalePrice')
kaggle = pd.read_csv('Test6_3.csv')
y_price = np.log(y_price)
xgdmat = xgb.DMatrix(data, y_price) # Create our DMatrix to make XGBoost more efficient
testFinaldmat = xgb.DMatrix(kaggle)

In [39]:
our_params = {'eta': 0.1, 'seed':0, 'subsample': 0.8, 'colsample_bytree': 0.8, 
             'objective': 'reg:linear', 'max_depth':3, 'min_child_weight':1} 

final_gb = xgb.train(our_params, xgdmat, num_boost_round = 432)
prediction = final_gb.predict(testFinaldmat)

In [40]:
GBoost = GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05,
                                   max_depth=4, max_features='sqrt',
                                   min_samples_leaf=15, min_samples_split=10, 
                                   loss='huber', random_state =5)
GBoost.fit(data,y_price)
predFinalBoost = GBoost.predict(kaggle)


In [41]:
alpha = 10
rg = Ridge(alpha = alpha)
rg.fit(data, y_price)
y_pred_rg = (rg.predict(kaggle))

In [42]:
fwd = forward()
fwd.fit(data, y_price)
predforward = fwd.predict(kaggle)

In [43]:
finalprediction = (np.exp(predFinalBoost)+np.exp(prediction)+np.exp(y_pred_rg)+np.exp(predforward))/4

In [45]:
#This is for the indices
ind = np.arange(1,1609)
headers = ['Id','Prediction']
prediction2 = pd.DataFrame({'Id':ind, 'Prediction':finalprediction})
#Saving results into CSV file 
prediction2.to_csv("Day8_2.csv", index=False)

# Standardising variables

In [3]:
from sklearn.preprocessing import StandardScaler

In [32]:
data = pd.read_csv('Train6_1.csv')
y_price = data.pop('SalePrice')
kaggle = pd.read_csv('Test6_1.csv')
y_price = np.log(y_price)

xgdmat = xgb.DMatrix(data, y_price) # Create our DMatrix to make XGBoost more efficient
testFinaldmat = xgb.DMatrix(kaggle)

In [5]:
our_params = {'eta': 0.1, 'seed':0, 'subsample': 0.8, 'colsample_bytree': 0.8, 
             'objective': 'reg:linear', 'max_depth':3, 'min_child_weight':1} 

final_gb = xgb.train(our_params, xgdmat, num_boost_round = 432)
prediction = final_gb.predict(testFinaldmat)

In [33]:
standardized_X = preprocessing.scale(data)

In [34]:
GBoost = GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05,
                                   max_depth=4, max_features='sqrt',
                                   min_samples_leaf=15, min_samples_split=10, 
                                   loss='huber', random_state =5)
GBoost.fit(standardized_X,y_price)
predFinalBoost = GBoost.predict((preprocessing.scale(kaggle)))


In [35]:
np.exp(predFinalBoost)

array([  98845.06069817,  161836.08983563,  134721.13762856, ...,
         90420.67745591,  195673.58716331,  202616.8345671 ])

In [37]:
alpha = 10
rg = Ridge(alpha = alpha)
rg.fit(standardized_X, y_price)
y_pred_rg = (rg.predict((preprocessing.scale(kaggle))))

In [38]:
np.exp(y_pred_rg)

array([ 101831.9046258 ,  164538.23211735,  133406.12748813, ...,
         84612.12449918,  201589.42172868,  212192.99267397])

In [40]:
fwd = forward()
fwd.fit(data, y_price)
predforward = fwd.predict(kaggle)

In [41]:
finalprediction = (np.exp(predFinalBoost)+np.exp(prediction)+np.exp(y_pred_rg)+np.exp(predforward))/4

In [42]:
finalprediction

array([  98877.65676872,  162746.06792677,  137250.78694504, ...,
         85610.19138503,  198510.80475612,  211307.75479618])

In [43]:
#This is for the indices
ind = np.arange(1,1609)
headers = ['Id','Prediction']
prediction3 = pd.DataFrame({'Id':ind, 'Prediction':finalprediction})
#Saving results into CSV file 
prediction3.to_csv("Day8_3.csv", index=False)

In [44]:
data = pd.read_csv('Train6_1.csv')
final_train = data.sample(frac=0.6, random_state=1)
final_test = data[data.index.isin(final_train.index)==False]
final_train.head()
y_train = final_train.pop('SalePrice')
y_test = final_test.pop('SalePrice')
y_train = np.log(y_train)

In [45]:
cv_params = {'max_depth': [3,5,7], 'min_child_weight': [1,3,5]}
ind_params = {'learning_rate': 0.1, 'n_estimators': 1000, 'seed':0, 'subsample': 0.8, 'colsample_bytree': 0.8, 
             'objective': 'reg:linear'}
optimized_GBM = GridSearchCV(xgb.XGBRegressor(**ind_params), 
                            cv_params, 
                             scoring = 'neg_mean_absolute_error', cv = 5, n_jobs = -1) 
# Optimize for accuracy since that is the metric used in the Adult Data Set notation

In [ ]:
optimized_GBM.fit(final_train, y_train)

In [ ]:
optimized_GBM.grid_scores_